name: lets-plot-experiments
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.8
  - geopandas
  - jupyter
  - kotlin-jupyter-kernel
  - numpy
  - pandas
  - pip
  - r-ggplot2
  - scipy
  - pip:
    - jupyter-ai
    - lets-plot