name: lets-plot-experiments
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.8
  - geopandas
  - ipynb-py-convert
  - jupyter
  - kotlin-jupyter-kernel
  - numpy
  - openai
  - pandas
  - polars
  - pillow
  - pip
  - r-irkernel
  - r-ggplot2
  - r-ggridges
  - r-mapproj
  - r-maps
  - r-hmisc
  - r-rnaturalearth
  - r-quantreg
  - scipy
  - seaborn
  - shapely
  - tornado=6.1
  - pip:
    - lets-plot