name: lets-plot-experiments
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.10
  - cairosvg
  - geopandas
  - jupyterlab
  - kotlin-jupyter-kernel
  - numpy
  - pandas
  - pip
  - pyarrow
  - r-ggplot2
  - r-irkernel
  - r-recommended
  - scipy
  - pip:
    - lets-plot
    - shap
    - shapely>=2.0.0
