name: lets-plot-experiments
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - jupyter
  - numpy
  - pandas
  - pip
  - r-irkernel
  - r-ggplot2
  - scipy
  - seaborn
  - pip:
    - lets-plot